### ISSUE TITLE
Blackboard Notification

### ISSUE THREAD

**Issue by FHellmann** [Fachschaft07/fs-app#10]
If a new entry is pushed to the blackboard the user should be informed on the phone via a notification.

**Comment by FHellmann** [comment]
The library [PugNotification](https://github.com/halysongoncalves/pugnotification) should do it.

**Comment by FHellmann** [comment]
@jqbbq The rest service should have the possibility to retrieve only the upcoming blackboard news (like in the last 60 minutes). Otherwise the data will be to big and slow to ask the server (every 5-10 minutes) if there is something new.

**Comment by thomai** [comment]
How about parameterizing the rest request with a time in seconds? Hardcoded minutes are bad because minutes are very inaccurate and a hardcoded amount of time is not very useful (just imagine a smartphone downtime for 5 minutes...)

**Comment by FHellmann** [comment]
I don't understand the needing for a parameter with seconds... Could you discribe it more, please?

<hr>
I thought something like the following:

Client (calls every 5-10min) --> http://fs.cs.hm.edu/rest/api/1/blackboard/notify --> Server

Server -->
```json
[
   { "title" : "Message Title 1"},
   { "title" : "Message Title 2"}
]
```
or
```json
[]
```
--> Client

**Comment by thomai** [comment]
Yup, and what happens if the device is offline for an hour? Probably the device would skip a bunch of blackboard entries.

**Comment by FHellmann** [comment]
Ok, now I know what you mean. A parameter is necessary to say when was the last request :)

**Comment by FHellmann** [comment]
Should be working with the next rest service release [v0.9.2](https://github.com/Fachschaft07/fs-rest/releases/tag/v0.9.2).
