### ISSUE TITLE
Dead app links after update to beta version

### ISSUE THREAD

**Issue by thomai** [Fachschaft07/fs-app#18]
There was only one icon in the app menu before. Now there is an additional one: Student Council 07... That would be okay if the old icon wouldn't be there anymore but It's impossible to remove it.

I've got a few ideas:
- Probably the problem is that I am a beta tester now, and this was the first beta-update.
- I could imagine that there is a bug in the new English language support.
- I've got an OnePlus One with Cyanogen OS (English system)

**Comment by thomai** [comment]
I think, it would be better to use the same app name for all languages. This would avoid bugs like this one ;-)

**Comment by FHellmann** [comment]
Does anyone else has this issue?

**Comment by FHellmann** [comment]
[http://stackoverflow.com/questions/17360731/application-is-not-installed-error-when-launched-from-home-screen-shortcut](http://stackoverflow.com/questions/17360731/application-is-not-installed-error-when-launched-from-home-screen-shortcut)

**Comment by thomai** [comment]
Another one :-) http://stackoverflow.com/questions/4226132/app-not-installed-error-on-android

**Comment by thomai** [comment]
The renamed app icon didn't fix my problem. The old app icon was named "Fachschaft07" without a space character ;-) The current one contains a space...

**Comment by FHellmann** [comment]
Of course it does... I will change it ;)
