### ISSUE TITLE
Yellow "Rate us" tile on the homescreen. 

### ISSUE THREAD

**Issue by CatCookie** [Fachschaft07/fs-app#22]
.. I don't like it. ;)

Maybe give the user an option to disable it in the settings of the homescreen.

**Comment by thomai** [comment]
What about a simple wipe gesture to disable it?

**Comment by FHellmann** [comment]
The user should be animated to rate the app. ;)
I've put the "Rate us" tile at the bottom of all other tiles... is that enough?

**Comment by CatCookie** [comment]
I think it is unnecessary harassment of the user. 
Placing a big yellow "rate us!" on the main screen is on the same level as ads.
*notamused*

**Comment by FHellmann** [comment]
Ok, I will remove the "Rate us" tile.

**Comment by thomai** [comment]
You could place the rating link in the "info" area (found in the menu). This wouldn't disturb anyone :-)
