### ISSUE TITLE
Homescreen blackboard entries clickable

### ISSUE THREAD

**Issue by CatCookie** [Fachschaft07/fs-app#23]
maybe also the lost and found tile clickable as a whole (not just the "show" button)

**Comment by FHellmann** [comment]
This would not match the [Matieral Design Guidelines](https://www.google.com/design/spec/components/cards.html#cards-content).

**Comment by CatCookie** [comment]
I thought it would behave like the old fashioned ListView ;)

Then you should separate the cards more and mak a bigger spacing. (like on the pictures in you link)

**Comment by FHellmann** [comment]
This will be done, after my [PR](https://github.com/dexafree/MaterialList/pull/98) to the library I used for will be merged and the new version published.
