### ISSUE TITLE
Timetable configurator with spinners

### ISSUE THREAD

**Issue by thomai** [Fachschaft07/fs-app#29]
There are a few usability flaws:
- A list of all available student groups would be helpful
- When I type in my student group, I have to press the button next to the text field. The Android keyboard return button does not work.
- The keyboard does not disappear after pressing this button
- When the timetable download is finished, you have to go back on your own... A button "Finish" or something like this would be useful.
- "Edit" to download a timetable is not suitable.

Summarized: The timetable is not usable enough for dumb students like me ;-)

Idea: @0711Picknicker implemented an assistant to guide the user through the timetable functionalities by giving them a hand at the first time they use the timetable.

**Comment by FHellmann** [comment]
Does the current timetable version fit your vision? Or do you want a timetable wizard anyway?

**Comment by thomai** [comment]
For now, you could replace the initial (empty) timetable with a direct link to the lesson selection activity.
In my view, the textfield to search for the study group is another usability flaw. Just use a dropdown menu ;-)
