### ISSUE TITLE
Change title picture in navigation sidebar

### ISSUE THREAD

**Issue by thomai** [Fachschaft07/fs-app#31]
I think a picture of the Fachschaft would be more appropriate. The Red Dice is representative for the whole University, so we could discuss about a new picture. Do you have an alternative?

**Comment by FHellmann** [comment]
This was just the first picture I think of, when I thought about the faculty 07. If you have another - better - one, let me know. ;)

**Comment by CatCookie** [comment]
You can try 
//Dropbox/Fachschaft/Bilder/IMG_8194.jpg

**Comment by thomai** [comment]
Looks good :-)

**Comment by thomai** [comment]
+wontfix, -discuss and closed issue? Why?

**Comment by FHellmann** [comment]
nobody want's to discuss...^^

**Comment by FHellmann** [comment]
This image looks a little bit to dark and unfriendly - in my opinion...

**Comment by thomai** [comment]
@CatCookie Another, more colorful idea?

**Comment by CatCookie** [comment]
nope... leave it as it is
