### ISSUE TITLE
Release date/beta update

### ISSUE THREAD

**Issue by thomai** [Fachschaft07/fs-app#32]
I would like to know when do you plan the release and if you can update the app once again in the play store for the beta testers in the next few days.

**Comment by FHellmann** [comment]
I plan the release date on the 01.10. The next beta release should be today...

I don't know, if I am able to implement/realize all the issues for the next release - currently I don't think so. I would implement and fix the basic features for the next release (2.0) and go on with additional features with the next version.

**Comment by thomai** [comment]
Are there some easy issues which would allow me to help with my "extraordinary Android skills"?

**Comment by FHellmann** [comment]
You could try issue #22.

**Comment by FHellmann** [comment]
I've documented the release date at the [milestones](https://github.com/Fachschaft07/fs-app/milestones).
