### ISSUE TITLE
Timetable not scrollable horizontally in portrait mode

### ISSUE THREAD

**Issue by thomai** [Fachschaft07/fs-app#34]
In my timetable are no entries, but I think it should be scrollable horizontally nevertheless.

**Comment by FHellmann** [comment]
This is not a bug, this is a feature! ;)

It's not supported yet to scroll horizontally.

**Comment by thomai** [comment]
Since the portrait mode is useless without scroll support, you should switch to landscape mode and disable portrait mode completely in this activity.

**Comment by FHellmann** [comment]
I don't think it's useless, because when I want to know the lessons of today, the other days aren't important.

**Comment by ckanitz** [comment]
please add horizontal scroll... you may could implement it with a settingsoption
