### ISSUE TITLE
Timetable shows weird data/days

### ISSUE THREAD

**Issue by thomai** [Fachschaft07/fs-app#41]
Very confusing... "Modellbasierte Softwareentwicklung" is on Tuesday... Not Thursday :-P

![screenshot_2015-10-01-16-35-12](https://cloud.githubusercontent.com/assets/6260106/10223664/7ae861aa-685a-11e5-912f-bb579b48e0e8.png)

**Comment by FHellmann** [comment]
That's not correct. The lessons are on Thursday. [See here](http://fi.cs.hm.edu/fi/rest/public/timetable/group/ig). ;)

**Comment by thomai** [comment]
You're right, thanks ;-) And what about Thursday->Friday->Saturday->Thursday->Friday? ;-)

**Comment by FHellmann** [comment]
See PR #38 ;-)
