### ISSUE TITLE
Timetable not up to date

### ISSUE THREAD

**Issue by wbmatti** [Fachschaft07/fs-app#42]
It seems that there is a problem with the REST API
Especially for the courses of Scientific Computing.
If you enter the group IC1 you get the courses of IF1B instead of IF1A (for example SE1)

Problem could be that IF1C was deleted.
Maybe only a cache problem?

**Comment by jqbbq** [comment]
Yes, probably a caching Problem. I will habe a lock at it.

**Comment by FHellmann** [comment]
@jqbbq is this issue resolved by the rest service?

**Comment by jqbbq** [comment]
Unfortunately I have not had the time to clear the cache yet.

**Comment by jqbbq** [comment]
I cleared all timetable caches, so with the next request the rest-service will fetch the current timetable from the fi.cs.hm.edu site.
I will also add an optimized cache scheduler to the rest-service with the next version.
