### ISSUE TITLE
timetable intersections wont show

### ISSUE THREAD

**Issue by ckanitz** [Fachschaft07/fs-app#45]
with the missing edit options it's impossible to manage intersections also the intersection will not show up

for example there're two tutoriums of two student groups and one of them intersects with an FWP i want to join the lesson of group B and tutorium of A i'm forced to download all entries of the timetable of A and B and my FWP entry got lost

**Comment by FHellmann** [comment]
Is this feature necessary? I don't know, if that use case make sense due to the fact, that you only can visit one (not two) lesson at the same time.

**Comment by ckanitz** [comment]
yes it is. At first: the main problem is, that the download of another timetable overwrites the existing ones. Also let's say you repeat Analysis and wan't to take as many lectures as possible but one date intersects with another lecture you take this other lecture primary on this day. But if the other lecture is canceled on one day I may wan't to join the extra Analysis lesson. This example works for extra practical lessons as well.

**Comment by FHellmann** [comment]
Ok, I will have a look at the realization of this new feature.

**Comment by thomai** [comment]
I've got the same problem, thanks @ckanitz
