### ISSUE TITLE
Parse timetable for department 10

### ISSUE THREAD

**Issue by thomai** [Fachschaft07/fs-app#9]
The timetable for the department 10 does not work. Probably it's a parsing problem because of weird changes in the code of the timetable website.

**Comment by FHellmann** [comment]
Fixed with the [LessonFk10Fetcher](https://github.com/Fachschaft07/fs-app/blob/dev/app/src/main/java/edu/hm/cs/fs/app/datastore/web/LessonFk10Fetcher.java) class.
